# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wim2tiZlmMDXNC2n_dedeKbz_OIWFzIq
"""

import re

text = "Свяжитесь с нами: Иван (123-456-7890), Мария 987-654-3210, офис: 555-111-2222. Неверный: 12-34-567."

# Паттерн для телефонного номера XXX-XXX-XXXX
pattern = r'\d{3}-\d{3}-\d{4}'

# Поиск всех совпадений
phone_numbers = re.findall(pattern, text)

# Вывод результата
print("Исходный текст:", text)
print("Найденные номера:", phone_numbers)

data_text = """
Посетите наши страницы:
Email: info@example.com (главный), support-team@corp.net (поддержка)
Дата: 25-05-2023, 01/01/2024, 12.02.2025.
Коды товаров: ID_PROD-1001, ITEM-20-A, ID-300-B.
Суммы: $150.50, 20 EUR, 500 RUB, £75.
"""

